# Setup
# aaatagline:      Welcome to Marsha's Blog
title:        Marsha Xue
tagline:      Expert on Lean Agile transformation for global company <br>More than 16 years' engineering domain knowledge from technical to team management.<br> 规模化敏捷(Scaled Agile Inc. – SAFe 4.0) 认证和授权的企业规模化敏捷转型咨询专家。 <br> 规模化敏捷高级Scrum Master以及产品经理培训认证教师。<br> 超过16年的跨国企业工作积累了流程再造和团队建设等方面丰富的实战经验。
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       marsha.xue
  url:        https://github.com/marshax

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
