# Setup
title:        Marsha's Blog
tagline:      Welcome to Marsha's Blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       marsha.xue
  url:        https://github.com/marshax

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
