# Setup
# aaatagline:      Welcome to Marsha's Blog
title:        Marsha's Blog
tagline:      I am an expert on Lean Agile transformation for global company with more than 16 years' engineering domain knowledge from technical to team management.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       marsha.xue
  url:        https://github.com/marshax

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
